name: youtube_downloader
description: "A new way to download your mp3 or mp4 youtube videos without ads."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  flutter_launcher_icons: ^0.14.3
  permission_handler: ^11.4.0
  path_provider: ^2.1.5
  open_file: ^3.5.10
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: 1.3.0
  youtube_explode_dart: ^2.3.10
  get: ^4.7.2
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android:
    enable: true
  windows:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/
